### ISSUE TITLE
Scenario 7: Set up the list of reviewers authorised to submit proposals to a discussion topic

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/PGT_govbot#11]
**Entry point:** NOT FOUND

**User Story**
As a admin 
I want to set who can create proposals for a topic
So that only authorized reviewers can submit proposals 

**Acceptance criteria**
OK
Given a valid topic name and list of reviewers categories
When the **Add Topic Proposers** button is executed
Then the list of allowed proposers for the topic is set, and a confirmation message is shown

KO
Given an invalid topic name or reviewer category name
When the **Add Topic Proposers** button is executed
Then the system returns an error message indicating the issue

**User type:** Admin / Admin discord channel

**Comment by CristinaEche** [comment]
@iluxonchik  Could not find this scenario or action button, please let me know if it is under other channel or management button

**Comment by iluxonchik** [comment]
Hello. It's under "SME Groups (comma-separated names)". You can find it when creating and editing a topic. There, just enter the names of the groups which are allowed to create proposals under that topic (empty means everyone is allowed).

Hope this answers your question, if not, please let me know.

As an action step, I can make the label/description of that field clearer, what do you think?


<img width="704" alt="7-1" src="https://github.com/user-attachments/assets/63473fad-68c2-48f6-aaea-44402ef1a4fd">
<img width="498" alt="7-2" src="https://github.com/user-attachments/assets/15d645ac-d78f-4430-a455-7a7b1cb7cdfa">
<img width="486" alt="7-3" src="https://github.com/user-attachments/assets/2910baac-4381-4767-91ac-0bef2f6c7680">
<img width="514" alt="7-4" src="https://github.com/user-attachments/assets/127f7f4c-aee9-471e-88e2-c0222c20d57b">
<img width="455" alt="7-5" src="https://github.com/user-attachments/assets/3aeb93dd-d1d1-4a49-a71b-cc8ca3214c0a">

**Comment by CristinaEche** [comment]
@iluxonchik  

Ohh that is the why of that field, I was not sure what to put there!! 

I totally agree with your proposal to make the label/description of that field clearer, however I had the feeling that the Admin had to select user by user so a drop down list similar to the others would be more practical, what do you think? .. imagine having like 10 groups, you need to memorize all the names...

**Comment by remigiusz-antczak** [comment]
I created a new topic called "topic2" and allowed only one existing SME/Reviewer group called "reviewers-group" and received a positive response:
`✅ Topic 'topic2' created successfully`

<img width="439" alt="image" src="https://github.com/user-attachments/assets/3e624049-76dd-4a15-9c02-b000aa3dd1b0">

Then, I tried to create another topic called "topic3" and allowed only one SME/Group with a made-up name called "reviewers-group2" and received a correct response:
` 🚫 An error occurred while creating the topic 'topic3': The following SME groups were not found: reviewers-group2`

<img width="1002" alt="image" src="https://github.com/user-attachments/assets/c1f373f2-1b17-45b4-a6d6-aa5ef080deda">

Proof:


https://github.com/user-attachments/assets/5d13c618-60b3-4d1d-86dc-90d1a73c6a33


Comments:
1. Please unify error messages as much as possible, as discussed in the [other threads](https://github.com/MinaFoundation/PGT_govbot/issues/23). 
2. Please verify if showing a drop-down menu with available SME/Reviewer groups for users to select from is possible. It would be easier than remembering or copy-pasting these names every time.

**Comment by iluxonchik** [comment]
> @iluxonchik
> 
> Ohh that is the why of that field, I was not sure what to put there!!
> 
> I totally agree with your proposal to make the label/description of that field clearer, however I had the feeling that the Admin had to select user by user so a drop down list similar to the others would be more practical, what do you think? .. imagine having like 10 groups, you need to memorize all the names...

Discord doesn't allow to have dropdown selection field in the forms(modals). What I can do, is add a follow-up to the modal, asking to select a limit to the users that can post under that topic (akin to "Set <Phase Name>", when setting the duration of the various phases)

**Comment by CristinaEche** [comment]
@iluxonchik  can you show an example? or maybe we can reconsider having this in a separated CTA?

CC: @remigiusz-antczak @es92

**Comment by CristinaEche** [comment]
@iluxonchik  Same as mentioned before, can we please have an autofill option here as well. tks
