### ISSUE TITLE
Scenario 8:  Draft proposal - Create a new proposal / Scenario 8.1: Manage drafts /  Scenario 8.2: delete proposal / 

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/PGT_govbot#12]
**Scenario 8: Draft proposal - create a new proposal**

**Entry point:** Propose channel, create new proposal button

**User story**
As a proposer
I want to draft a proposal
So that it can be reviewed and voted on

**Acceptance criteria**
OK
Given a valid proposal name, budget and forum URL
When the create new proposal button is executed
Then the proposal is drafted and ready for review

KO
Given an invalid forum URL
When the create new proposal button is executed
Then the system returns an error message indicating the issue

-

**Scenario 8.1: Manage drafts**

**Entry point:** Propose channel, manage drafts button, select proposal from list and Edit proposal button

**User story**
As a proposer
I want to manage a drafted a proposal
So that it can be edited and then submitted to a funding round

**Acceptance criteria**
OK
Given a valid proposal name, selected from the list
When the Edit proposal button is executed
Then the proposal modal is shown, and the edition can be performed and submitted

KO
only if invalid forum URL

-

**Scenario 8.2: delete proposal**

**Entry point:** Propose channel, manage drafts button, select proposal from list and delete proposal button

**User story**
As a proposer
I want to remove  a drafted a proposal
So that it cannot be edited or submitted to a funding round

**Acceptance criteria**
OK
Given a valid proposal name, selected from the list
When the remove proposal button is executed
Then the proposal confirm delete button is shown, by clicking it the removal can be performed, a success deletion message will appear 

KO
if trying to click the cancel button to cancel the request after confirming the deletion, it will show a proposal not found message since the proposal is already deleted 

**User type:**  admin / community member in the proposals channel

**Comment by remigiusz-antczak** [comment]
Scenario 8: Draft proposal - create a new proposal

I managed to create a new proposal successfully:
<img width="547" alt="image" src="https://github.com/user-attachments/assets/02e1d338-65da-49bb-ad21-b855c8c88b89">

I also received a correct response when pasting a wrong URL in the creation form:
<img width="708" alt="image" src="https://github.com/user-attachments/assets/039d5384-77b9-43f5-ad9b-5b2b8579d5e0">


Scenario 8.1: Manage drafts

I managed to successfully change the parameters of a proposal from this:
<img width="551" alt="image" src="https://github.com/user-attachments/assets/04d19e0c-c078-42ca-8eaf-ff17c3938c36">

to this (changed name, budget, and URL):
<img width="557" alt="image" src="https://github.com/user-attachments/assets/e489beb3-0d82-45be-8d88-e3be665275a7">

I also received a correct response when editing the URL to the wrong one:
<img width="676" alt="image" src="https://github.com/user-attachments/assets/365053a3-49f7-4f9d-9dcc-933d534b858d">


Scenario 8.2: delete proposal

I successfully managed to delete a proposal:
<img width="426" alt="image" src="https://github.com/user-attachments/assets/7d7a8817-1e69-4527-bcc2-1e9bc9f48dbc">

I also clicked again the cancel button to cancel the request after confirming the deletion, and it showed me a correct response:
<img width="392" alt="image" src="https://github.com/user-attachments/assets/63efeee4-4f67-4daa-9590-25f9e21284cf">


Proof:


https://github.com/user-attachments/assets/1ba9b884-aa1f-49cf-a435-2f0d90681252


Comments:
1. Please unify error messages as much as possible, as discussed in the [other threads](https://github.com/MinaFoundation/PGT_govbot/issues/23).

**Comment by iluxonchik** [comment]
Ack

**Comment by CristinaEche** [comment]
@iluxonchik 
We have the latest deployment on discord testing server (Released Aug, 6th 11pm CET).

In the proposal section, in the main buttons, please organize the order of the buttons and rename them: 

<img width="804" alt="image" src="https://github.com/user-attachments/assets/c71c0fbc-8ca9-4014-9ce3-7e735a81eca2">

Organize and rename them like this:

1- Create Proposal Draft
2- Manage Drafts
3- Submit Proposal 
4- Manage Proposals

In the Proposal Management description please update to:

Proposal Management
Welcome to the Proposal Management channel. Here you can: create a proposal draft, manage the drafts, submit proposals to funding rounds and manage the submitted proposals.

**Comment by CristinaEche** [comment]
@iluxonchik 

when managing drafts, the remove option should be at the end in right side

<img width="866" alt="image" src="https://github.com/user-attachments/assets/1b11e657-5551-4df8-8fcb-38667c655f9f">
