### ISSUE TITLE
Scenario 10:  Funding Round Activation - Request / Scenario 10.1: Funding Round Activation - Approval / Scenario 10.2: Funding Round Activation - Rejection

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/PGT_govbot#14]
**Scenario 10: Funding Round Activation - request** 

**Entry point:** Funding round channel, activate funding round and select round from the list 

As a reviewer
I want to vote for the activation of a funding round
so that I can indicate my interest in the funding round

Given A funding round name,
When I use the **Funding Round Activation** button 
Then the vote should be cast successfully, and the round should be activated, a successful message should be provided.

Given An invalid funding round name or link
When  I use the Funding Round Activation button
Then the system should return an error message indicating the failure to cast the vote

**_NOTE: all of the members of the committee have to vote for the activation, members of the committee are set in the Topic, **we need to make sure they receive a notification that they have pending votes**_**

- 

**Scenario 10.1: Funding Round Activation - Approval**

**Entry point:** Admin channel, approve funding round and select round from the list 

**User story**
As an Admin user
I want to approve the activation of a funding round
so that the requester or any other authorized person can add a proposal to the round

**Acceptance criteria**
OK
Given A funding round name and a link to vote
When I use the Funding Round Approval button 
Then the vote should be cast successfully, and the round should be activated, a successful message should be provided.

KO
Given An invalid funding round name or link
When  I use the Funding Round Approval button
Then the system should return an error message indicating the failure to cast the vote

**_NOTE: an admin have to approve the activation of the funding round, **we need to make sure they receive a notification that they have pending approvals/rejections**_**

-

**Scenario 10.2: Funding Round Activation - Rejection**

**Entry point:** Admin channel, reject funding round and select round from the list 

**User story**
As an Admin user
I want to reject the activation of a funding round
so that the requester can review, resubmit or delete the round activation

**Acceptance criteria**
Given A funding round name and a link to vote
When I use the Funding Round Rejection button 
Then the vote should be cast successfully, and the round should be activated, a successful message should be provided.

Given An invalid funding round name or link
When  I use the Funding Round Rejection button
Then the system should return an error message indicating the failure to cast the vote

**_NOTE: an admin have to approve the activation of the funding round, **we need to make sure they receive a notification that they have pending approvals/rejections**_**

Users tupe: Admin and reviewer - Admin and fund init channel

**Comment by CristinaEche** [comment]
@iluxonchik
I could not reproduce the process,  please confirm if the above is the right flow in order to start testing . tks!

**Comment by remigiusz-antczak** [comment]
_**Bug**_ 
Scenario 10: Funding Round Activation - request

I couldn't vote to approve an existing voting round. I managed to do that earlier with another funding round, but I don't understand why I couldn't do it with a new funding round. My suspicion is that I was testing setting unrelated dates for phases, and maybe that caused the bot to act weird. 

Proof:


https://github.com/user-attachments/assets/d974f676-e74d-4235-a70d-773837297cd6


Comments:
1. Is there a need for more error handling? I couldn't cast my vote for a newly created funding round, but I managed to do it correctly when doing a "dry test" (before recording). It looks like an issue with the dates I set for the new funding round. 

I set a new funding round with the correct dates (I think) and still couldn't cast a vote, even though it worked for this one time I tested before recording

Proof:


https://github.com/user-attachments/assets/48c5e3c5-a7d6-4b9c-8e69-ef216690e44c

**Comment by CristinaEche** [comment]
From discord message: illya — Today at 3:04 PM

> responding to Cristina: 
> so the process to activate founding round is: 
> > first activate round in funding-round channel
> > and then admin approves in admin channel? 

1. #funding-round-init --> zkignite-facilitators start and vote on the funding round
2. Once enough votes are in, in #admin, the funding round is approved. Once it's approved, it's active

CC: @remigiusz-antczak  @iluxonchik

**Comment by CristinaEche** [comment]
@iluxonchik 

We finally managed to test the scenario, we were missing the fact that the committee set in the topic has to approve the activation as you mentioned. The issue we encounter is that no one was receiving a notification to vote on the activation, so it was confusing on how to proceed, so here is a work around please let us know if it is viable or let us know another possible solution:

Create 2 channels:

1. Channel name : Pending-funding-activations; to receive notifications of when a request to vote on a funding activation is needed. Profile/role: reviewers /ignite ppl / authorized ppl
2. Channel name: pending-funding-round-approvals. Only for admins.

Once a funding round is opened/approved, then the forum channel should be created and the submitted proposals should be shown in there. This connects on what we discussed about the forums and your testing:

![image](https://github.com/user-attachments/assets/8832c47e-7e00-420b-88cf-424b63801c18)
cc: @remigiusz-antczak

**Comment by iluxonchik** [comment]
Hey @CristinaEche  @remigiusz-antczak,

I will attempt to replicate the issue, but it looks like some issue in a branch of the code. Either the funding round shouldn't have been shown for voting in the first place, or the passage of data between actions (in the code) is incorrect. 

Regarding:
```
Channel name : Pending-funding-activations; to receive notifications of when a request to vote on a funding activation is needed. Profile/role: reviewers /ignite ppl / authorized ppl
```
The #funidng-round-int already handles that (with the "Vote" button), while also allowing to create funding rounds in the same place. 

I can add the channel that you requested, but perhaps correcting the logic or showing an appropriate error message would be sufficient.

Regarding:
```
Channel name: pending-funding-round-approvals. Only for admins.
```

How about I add this as button in the main screen of #admin? I believe there is space for one more button. I believe ultimately, the least channels possible is better.


Let me know what you think!

**Comment by CristinaEche** [comment]
@iluxonchik 

Hi I was trying to activate a funding roud, and it let me activate it, however i was not able to submit a proposal there:

<img width="642" alt="image" src="https://github.com/user-attachments/assets/41f0d03c-6312-486d-aee5-618c2b274553">

<img width="642" alt="image" src="https://github.com/user-attachments/assets/60baa85b-1dfd-4c2f-b6d1-5b6c685c719e">

**Comment by CristinaEche** [comment]
Solved, Funding rounds are approved after the reviewers have voted for the funding round activation. Approvals are done by the admin role.

The forum channel with the name of the funding round will indicate that a new funding round is coming.
So far a channel for reviewers will be created to manually send notifications.
