### ISSUE TITLE
Scenario 12: Proposal Consideration Phase Approve Project /  Scenario 12.1: Proposal Consideration Phase Reject Project / Scenario 12.2: Update consideration vote

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/PGT_govbot#16]
**Scenario 12: Proposal Consideration Approve project**

Entry points: Consider channel, select funding round button

**User story**

- User 1: Reviewer 

As a Reviewer 
I want  to vote for the consideration of a proposal in the active funding round
So that proposal can move to the next phase

**Acceptance criteria** 
Given that I clicked on the Select Funding Round button and selected funding round from the list 
When I execute the Evaluate Proposals button
Then a list of proposals is presented and I can choose which proposal to consider, a preview with the vote details is provided. By clicking on the Approve Project button, I write my reasoning,  the proposal gets approval and a confirmation message is provided.

KO
if there are no proposals to approve the evaluate button will be shown as inactive

-

**Scenario 12.1: Proposal Consideration Reject Project**

**Entry points: Consider channel, select funding round button**

**User story**

- User 1: Reviewer 

As a Reviewer 
I want  to reject my vote for the consideration of a proposal in the active funding round
So that proposal can’t move to the next phase

**Acceptance criteria** 
Given that I clicked on the Select Funding Round button and selected funding round from the list 
When I execute the Evaluate Proposals button
Then a list of proposals is presented and I can choose which proposal to consider,  a preview with the vote details is provided. By clicking on the Reject Project button, I give my reasoning, the proposal gets rejected and a confirmation message is provided.

-

**Scenario 12.2: Update consideration vote**

**Entry points: Consider channel, select funding round button**

**User story**

- User 1: Reviewer 

As a Reviewer 
I want  to update my vote for the consideration of a proposal in the active funding round
So that proposal can or can’t move to the next phase

**Acceptance criteria** 

- Approve (when rejected)

Given that I clicked on the Select Funding Round button and selected funding round from the list 
When I execute the Update Vote button
Then a list of proposals is presented  and I can choose which vote to update, by clicking on the Change to Approve button, I give my reasoning and the proposal gets approved and a confirmation message is provided.

- Reject (when approved)

Given that I clicked on the Select Funding Round button and selected funding round from the list 
When I execute the Update Vote button
Then a list of proposals is presented  and I can choose which vote to update, by clicking on the Change to Reject button, I give my reasoning and the proposal gets rejected and a confirmation message is provided.

User type: reviewer  - Consider discord channel.

-

Pending Scenario for OCV/Scenario 12B.: When a community member with >10% tokens wants to show interest in a proposal

**Comment by remigiusz-antczak** [comment]
I successfully tested the whole flow without any issues

Proof:


https://github.com/user-attachments/assets/87532a24-38fb-4312-bd30-a4167ac4ad0b


Comment: 

1. Make reviewing proposals more dynamic - Currently, the user can approve/reject one proposal and then must go through the whole flow again to vote on the next one. The same happens when changing a vote. Please review if we can make it more dynamic so that, for example, if there are over 20 proposals, users don't need to repeat the whole flow for every proposal. Maybe casting a vote should refresh the view with a success notification, with the possibility of changing it again or viewing the following proposal to cast/change a vote? Please see the Proof video above to see how it looks currently in practice

**Comment by CristinaEche** [comment]
For the MVP the OCV part was not considered.

The consideration Phase works as expected.

If anyone comments in a thread of a proposal, the proposal status info cannot be updated, but the proposal is indeed updated. to be reviewed in a Bug Issue.
