### ISSUE TITLE
OK/KO messages: Provide successful or unsuccessful messages for all the actions 

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/PGT_govbot#23]
@iluxonchik 

**1. Establish success confirmation messages for all OK** actions in all scenarios, so that the user is certain that the action has been performed.

Examples based on testing different scenarios:

-**Editing a committee member**
After successfully editing the number of members in a committee, there's no success message, which might confuse people since in the other sections (from previous testing scenarios) there are notification messages after executing any action.

-**Removing acommitte**
After successfully removing a committee, there's no success message, which might confuse people since, in the other sections (from previous testing scenarios), there are notification messages after executing any action.

**2. Unify KO/ error messages -** (it's also mentioned in the https://github.com/MinaFoundation/PGT_govbot/issues/7) Please review if we could unify the structure of error messages because it might confuse users, especially since some of these errors don't show too many details for users to understand what happened

**Comment by CristinaEche** [comment]
from @iluxonchik to @remigiusz-antczak  (via Discord)

I'll reply generally here since it's mentioned in several places. I will do what's feasible to unify the error messages, but it's not always possible. There are time limits to how much I have to edit messages, and I can only reply to user interactions. Also, not all of the forms are the same, so it's not always possible to render the error message on top. On the bottom, it's almost always possible. There is the options of deleting them, but then I need to store references to them.

Just to clarify: is sending error messages on the bottom acceptable?

**Comment by iluxonchik** [comment]
On Discord:

> so error and success messages on bottom are okay? 
- @iluxonchik 

> yes!
- @CristinaEche

**Comment by remigiusz-antczak** [comment]
Yes, thank you! Whatever we can do to improve it within possible options is highly appreciated 🙇
Is it possible for them to look similarly to the notification updates?
