### ISSUE TITLE
Scenario 1:  Create and manage a category / reviewers group

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/PGT_govbot#5]
**Entry point:** Reviewer Management Button in the admin channel

**User Story:** 
As a system administrator
I want to add a new reviewer category
So that I can organize reviewers into different groups

**Acceptance criteria:** 
OK
Given a valid group category name
When the reviewer management button is executed
Then a new reviewer category can be created

Given A new group category name
When I use the add new reviewer group button with the new group category name as input
Then A new group category should be created successfully

KO
Given an invalid or duplicate group category name
When the add new reviewer group button is executed
Then the system returns an error message indicating the issue

**User type:** Admin / Admin discord channel

**Comment by remigiusz-antczak** [comment]
I created a new group called "reviewers-group" and received a confirmation:
`✅ SME Group 'reviewers-group' created successfully`
Then, I tried to create another group with the same name ("reviewers-group" and received an error: 
`🚫 An error occurred while creating the group 'reviewers-group'`

Proofs:

- <img width="759" alt="image" src="https://github.com/user-attachments/assets/a15f0a04-b222-4f58-8e9c-3bc7dc3433ea">
- https://github.com/user-attachments/assets/a68b2fce-926b-4903-870c-9f89cc392b26

Comments:

1. Please change all occurrences of the word 'SME' to 'Reviewer' to unify it with the new naming of this role.

**Comment by iluxonchik** [comment]
Hello and acknowledged. Will make the change.

**Comment by CristinaEche** [comment]
@iluxonchik 

In the Admin section, in the description please add the new button information (Proposal Status Management). Also please rename the buttons:

<img width="897" alt="image" src="https://github.com/user-attachments/assets/a0108cce-3130-4c75-a93d-b3fc5bdb7466">

1- Manage Reviewers (please replace the word SME for reviewers in all the development) 
2- Manage Discussion Topics 
3- Manage Funding Rounds 
4- Manage Proposals Status 


in the Manage Reviewers flow, please update the SME names and descriptions with the Reviewer/Reviewers name

<img width="489" alt="image" src="https://github.com/user-attachments/assets/81fc3cd4-b78e-4cfc-98a2-fee8738adde5">

**Comment by CristinaEche** [comment]
In the create a Discussion Topic flow, can you please rename the button and update description to:

<img width="556" alt="image" src="https://github.com/user-attachments/assets/d4eb0dad-5b55-4fd0-b02c-6f5f0120a45e">

- Add Discussion Topic

- Manage Discussion Topics
Select a Discussion Topic from the list or add a new one. (Page 1/1)
