### ISSUE TITLE
Scenario 2:  Add reviewers

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/PGT_govbot#6]
**Entry point:** Drop down list from the manage reviewers groups message

**User Story**
As a system administrator
I want to add a new reviewer 
So that I can organize reviewers into different groups

**Acceptance criteria**
OK
Given a valid group, select the desired group from the dropdown list
When the manage member button is executed
Then the add member button can be executed and a new member can be added from the members drop down list, a confirmation message will be shown

KO
Given a duplicate member name is selected
When the add member button is executed
Then the system returns an error message indicating the issue

**User type:** Admin / Admin discord channel

**Comment by remigiusz-antczak** [comment]
I added new members to a group called "reviewers-group" and received a confirmation:
`Successfully added 3 member(s) to the group. 0 member(s) were already in the group and skipped.`
<img width="544" alt="image" src="https://github.com/user-attachments/assets/c34489d7-73a9-4a50-a856-af21fbd42bc1">

Then, I tried to add the same users as new members to a group called "reviewers-group", and I received a correct notification:
`Successfully added 0 member(s) to the group. 3 member(s) were already in the group and skipped.`
<img width="545" alt="image" src="https://github.com/user-attachments/assets/c2fbed4d-7c45-4565-a4c1-40ac5acb3bc4">

Then, I tried to add the same users plus a new one as members to a group called "reviewers-group", and I received a correct notification:
`Successfully added 1 member(s) to the group. 3 member(s) were already in the group and skipped.`
<img width="547" alt="image" src="https://github.com/user-attachments/assets/0fc022bc-be5e-4f79-95d9-25a1481eebaf">

Proof:
https://github.com/user-attachments/assets/bd55e680-5627-46ab-88bf-9dc37d2b8e64

Comments:
1. Unify colors - please review messages and buttons and unify their appearance. For example, 
   - When a user selects a group, they see two buttons: "Remove SME Group" and "Manage Members" 
   - After clicking "Manage Members," the user sees two buttons: "Add Members" and "Remove Member"
   - In the first view, the first button is red and indicates removal action; in the second view, the red button is the second
   I'd suggest the following order: Blue buttons (for navigating through the menu and sub-categories); Green buttons (for actions resulting in executing a specific functionality, for example, showing a pop-up modal, adding members, etc.); Red buttons (for actions resulting in removing or rejecting something, for example, removing members, etc.).
   - <img width="577" alt="image" src="https://github.com/user-attachments/assets/315b34c4-8d84-4ce5-9fb4-eb3eef7163b5">
   - The same for messages. For example, when managing members in a group, there are different notifications, such as whether a user adds new members, existing ones, new+existing, or removes some of them. All of them have the same green color. 
   I'd suggest a green color for the successful addition/deletion of members, yellow for when some proposed members are already in the group, and red if there was no positive result. All proposed members are already part of the group, and no one new was added or no one could be removed.

**Comment by iluxonchik** [comment]
ACK, thank you.

**Comment by CristinaEche** [comment]
@iluxonchik 

please update the order of the buttons:

<img width="556" alt="image" src="https://github.com/user-attachments/assets/9f6ebc8c-b3b2-4d6b-b36b-3ff5cae62fd9">

When the user has action buttons of manage and removal, or edit an remove, the remove button should go at the right side, meaning that is the last option.
