### ISSUE TITLE
Scenario 5 :  Remove Discussion topic

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/PGT_govbot#9]
**Entry point:** Topic management button from admin channel, select topic from drop down list and remove button

**User Story**
As a proposal admin
I want to remove a discussion topic
So that obsolete or redundant topics can be managed

**Acceptance criteria**
OK
Given a valid topic name 
When the Remove Topic button is executed
Then the specified Discussion topic is set to be removed, a removal confirmation button will be shown, a removal confirmation message will be shown

KO
Given a valid topic name 
When the Remove Topic button is executed
Then the specified discussion topic is set to be removed, the system returns an error message indicating the issue

**User type:** Admin / Admin discord channel

**Comment by remigiusz-antczak** [comment]
**(Incorrect behavior)** I tried to remove a topic called "topic2," but when asked for removal confirmation, I clicked `Cancel` button and got the following message:
`Invalid interaction type.`

<img width="382" alt="image" src="https://github.com/user-attachments/assets/e548b1ff-181f-421a-bb00-1ec30620edbf">

Then, I tried to complete the removal flow and successfully managed to remove a topic called "topic2," and received the following confirmation:
`Topic has been successfully removed.`

<img width="428" alt="image" src="https://github.com/user-attachments/assets/abdfc5c3-32de-44c5-aa21-7a72c60d0b80">

Proof:

https://github.com/user-attachments/assets/f70845db-71f6-4ab5-9922-0a97e5832e65

Comments:
1. Unify error messages (already mentioned [here](https://github.com/MinaFoundation/PGT_govbot/issues/8#issuecomment-2260901677) and [here](https://github.com/MinaFoundation/PGT_govbot/issues/7#issuecomment-2260025992))

**Comment by iluxonchik** [comment]
ACK, thank you.

**Comment by CristinaEche** [comment]
@iluxonchik 

Rename button to : Edit Discussion topic

<img width="556" alt="image" src="https://github.com/user-attachments/assets/cba089d2-93ac-425f-9ae6-ce34e1ee993f">

**Comment by CristinaEche** [comment]
This one is ok, will close the issue as completed. The button name is fine.
@iluxonchik
